'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
export default function SetPasswordPage() {
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { async function init() { const client = createClient(); if (!client) { setError('Acesso não configurado.'); return; } const code = new URLSearchParams(window.location.search).get('code'); if (code) { const { error } = await client.auth.exchangeCodeForSession(code); window.history.replaceState({}, '', '/definir-senha'); if (error) { setError('Link inválido ou expirado. Solicite outro na tela de login.'); return; } } const { data } = await client.auth.getUser(); if (!data.user) setError('Abra o link recebido por e-mail ou solicite outro na tela de login.'); else setReady(true); } void init(); }, []);
  async function save(e: React.FormEvent) { e.preventDefault(); if (password !== confirmation) { setError('As senhas precisam ser iguais.'); return; } setBusy(true); setError(''); try { const client = createClient(); if (!client) throw new Error('Conexão indisponível.'); const { error } = await client.auth.updateUser({ password }); if (error) throw new Error('Não foi possível salvar. Use uma senha de pelo menos 12 caracteres e tente novamente.'); window.location.assign('/escala'); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao salvar.'); setBusy(false); } }
  return <main className="min-h-screen grid place-items-center p-5"><form onSubmit={save} className="w-full max-w-md p-8 border border-border rounded-xl bg-card-bg space-y-5"><h1 className="text-2xl font-semibold">Defina sua senha</h1><p className="text-sm text-text-secondary">Use pelo menos 12 caracteres.</p>{error && <p role="alert" className="text-danger text-sm">{error}</p>}<label className="nv-label">Nova senha<input className="nv-input" type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e => setPassword(e.target.value)} /></label><label className="nv-label">Confirmar senha<input className="nv-input" type="password" autoComplete="new-password" minLength={12} required value={confirmation} onChange={e => setConfirmation(e.target.value)}/></label><button className="nv-button w-full" disabled={!ready || busy}>{busy ? 'Salvando…' : 'Salvar senha e entrar'}</button><a className="block text-sm text-primary" href="/login">Voltar ao login</a></form></main>;
}
